import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const main = () => {
  console.log('🔄 BƯỚC 4: GỘP TẤT CẢ DỮ LIỆU\n');

  // Load 3 file JSON
  const questionsPath = path.resolve(__dirname, './surveyQuestions.json');
  const templatesPath = path.resolve(__dirname, './habitTemplates.json');
  const suggestionsPath = path.resolve(__dirname, './habitSuggestions.json');

  // Kiểm tra file tồn tại
  const missingFiles = [];
  if (!fs.existsSync(questionsPath)) missingFiles.push('surveyQuestions.json');
  if (!fs.existsSync(templatesPath)) missingFiles.push('habitTemplates.json');
  if (!fs.existsSync(suggestionsPath)) missingFiles.push('habitSuggestions.json');

  if (missingFiles.length > 0) {
    console.error('❌ Thiếu các file:', missingFiles.join(', '));
    console.log('\n▶️  Chạy các script sau:');
    if (missingFiles.includes('surveyQuestions.json')) {
      console.log('   node src/Script/1_generateQuestions.js');
    }
    if (missingFiles.includes('habitTemplates.json')) {
      console.log('   node src/Script/2_generateTemplates.js');
    }
    if (missingFiles.includes('habitSuggestions.json')) {
      console.log('   node src/Script/3_generateSuggestions.js');
    }
    return;
  }

  // Load dữ liệu
  const surveyQuestions = JSON.parse(fs.readFileSync(questionsPath, 'utf-8'));
  const habitTemplates = JSON.parse(fs.readFileSync(templatesPath, 'utf-8'));
  const habitSuggestions = JSON.parse(fs.readFileSync(suggestionsPath, 'utf-8'));

  console.log(`📋 Câu hỏi: ${surveyQuestions.length}`);
  console.log(`💡 Templates: ${habitTemplates.length}`);
  console.log(`✨ Suggestions: ${habitSuggestions.length}\n`);

  // Tạo file seedSurvey.js
  const fileContent = `// Auto-generated by generateSeedData.js using Groq API
// DO NOT EDIT MANUALLY - Run generation scripts to regenerate

const surveyQuestions = ${JSON.stringify(surveyQuestions, null, 2)};

const habitTemplates = ${JSON.stringify(habitTemplates, null, 2)};

const habitSuggestions = ${JSON.stringify(habitSuggestions, null, 2)};

const targetPersonas = {
  'health-focused': {
    name: 'Người tập trung sức khỏe',
    description: 'Ưu tiên sức khỏe thể chất và tinh thần',
    categories: ['health', 'fitness', 'sleep', 'mindful']
  },
  'productivity-driven': {
    name: 'Người năng suất cao',
    description: 'Tập trung vào hiệu suất công việc',
    categories: ['productivity', 'learning', 'energy']
  },
  'knowledge-seeker': {
    name: 'Người ham học hỏi',
    description: 'Phát triển bản thân qua học tập',
    categories: ['learning', 'productivity']
  },
  'mindful-seeker': {
    name: 'Người tìm kiếm cân bằng',
    description: 'Quan tâm sức khỏe tinh thần',
    categories: ['mindful', 'health', 'sleep']
  },
  'finance-conscious': {
    name: 'Người có ý thức tài chính',
    description: 'Quản lý tài chính tốt',
    categories: ['finance']
  },
  'balanced-lifestyle': {
    name: 'Người sống cân bằng',
    description: 'Cân bằng công việc và cuộc sống',
    categories: ['health', 'productivity', 'social', 'mindful']
  },
  'fitness-enthusiast': {
    name: 'Người đam mê thể hình',
    description: 'Tập trung tập luyện',
    categories: ['fitness', 'health']
  },
  'social-connector': {
    name: 'Người quan hệ xã hội',
    description: 'Coi trọng mối quan hệ',
    categories: ['social']
  }
};

export {
  surveyQuestions,
  habitSuggestions,
  habitTemplates,
  targetPersonas
};
`;

  // Lưu file
  const outputPath = path.resolve(__dirname, './seedSurvey.js');
  fs.writeFileSync(outputPath, fileContent);

  console.log('='.repeat(60));
  console.log('🎉 HOÀN TẤT GỘP DỮ LIỆU!');
  console.log('='.repeat(60));
  console.log(`💾 Đã tạo file: ${outputPath}`);
  console.log(`\n📊 Thống kê:`);
  console.log(`   - ${surveyQuestions.length} câu hỏi khảo sát`);
  console.log(`   - ${habitTemplates.length} mẫu thói quen`);
  console.log(`   - ${habitSuggestions.length} gợi ý thói quen`);
  console.log(`\n▶️  Chạy seed vào database:`);
  console.log(`   node src/Script/seed.js`);
  console.log('='.repeat(60));
};

main();