/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot_password` | `/forgot_password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/habits/AddHabitModal` | `/habits/AddHabitModal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/habits/CreateHabitDetail` | `/habits/CreateHabitDetail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/habits/HabitStreak` | `/habits/HabitStreak`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/habits` | `/habits`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sleep/ai-chat` | `/sleep/ai-chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sleep` | `/sleep`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgot_password` | `/forgot_password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/habits/AddHabitModal` | `/habits/AddHabitModal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/habits/CreateHabitDetail` | `/habits/CreateHabitDetail`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/habits/HabitStreak` | `/habits/HabitStreak`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/habits` | `/habits`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sleep/ai-chat` | `/sleep/ai-chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sleep` | `/sleep`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgot_password${`?${string}` | `#${string}` | ''}` | `/forgot_password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/habits/AddHabitModal${`?${string}` | `#${string}` | ''}` | `/habits/AddHabitModal${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/habits/CreateHabitDetail${`?${string}` | `#${string}` | ''}` | `/habits/CreateHabitDetail${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/habits/HabitStreak${`?${string}` | `#${string}` | ''}` | `/habits/HabitStreak${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/habits${`?${string}` | `#${string}` | ''}` | `/habits${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sleep/ai-chat${`?${string}` | `#${string}` | ''}` | `/sleep/ai-chat${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sleep${`?${string}` | `#${string}` | ''}` | `/sleep${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot_password` | `/forgot_password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/habits/AddHabitModal` | `/habits/AddHabitModal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/habits/CreateHabitDetail` | `/habits/CreateHabitDetail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/habits/HabitStreak` | `/habits/HabitStreak`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/habits` | `/habits`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sleep/ai-chat` | `/sleep/ai-chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sleep` | `/sleep`; params?: Router.UnknownInputParams; };
    }
  }
}
